version: '3.1'
services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=localdevdb
      - POSTGRES_USER=localdevuser
      - POSTGRES_PASSWORD=pirate
